### PR TITLE
Add mrouted 3.9.8 package

### PR DESCRIPTION
**Pull request by elupus**
Add a package for building mrouted multicast routing daemon. This will allow routing of multicast between vpn tunnels, interfaces and internet.

 * Note: for tunnel support kmod-ipip would be needed as a dependency.
 * Note: by default the service is disabled.

### CODE REVIEW

**Comment by ryzhovau** [comment]
Thanks! 
Is this package was taken from some OpenWrt feed or it was written from scratch?

**Comment by elupus** [comment]
from scratch. looking at pimd too. but it requires kernel support that isnt
commonly there.

**Comment by ryzhovau** [comment]
Too late:) I've moved `mrouted` to [oldports feed](https://github.com/Entware-ng/entware-oldpackages-ports) because of `Copyright (C) 2006-2011 OpenWrt.org` in Makefie.

**Comment by elupus** [comment]
Ah. yea, since it was my first package I copied from another as a base. I
sort of expected some review resistance before merge 😀.

**Pull request merged**
